### ISSUE TITLE
Bug in the evaluation of an ensemble model

### ISSUE THREAD

**Issue by futakw** [AmirooR/IntraOrderPreservingCalibration#3]
https://github.com/AmirooR/IntraOrderPreservingCalibration/blob/79325ae321fc1bce3088b2af8ecd18357b50fb6a/evaluate.py#L207

Here, "model" is evaluated instead of "models", the list of k-models.
This results in evaluating the k-th model instead of an ensemble model.

**Comment by AmirooR** [comment]
Hi @futakw,

Yes, you are right. Thanks for pointing it out. I will update the code and check the results and update them if necessary.

**Comment by AmirooR** [comment]
Hi again @futakw,

I have updated the code and put the new results for the ECE metric in the Readme file. Our results for ECE are improved slightly. Note that the results for debiased ECE, and Marginal Calibration error were not affected with this bug.

Thanks again!
